---
title: "mortality"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(twang)
library(sandwich)
library(Matching)
setwd('C:/Users/Wesley/OneDrive - architect plug-and-play supply-chains/Desktop/Amsterdam database/transfusion_targets')

combined.data = read.csv("data/combined.csv")
```

```{r multivariate_logistic_regression, echo=FALSE, message=FALSE, warning=FALSE, results='hide'}
groups = c('7 to 8','8 to 9','9 to 10','10 to 12')

fit_glm = function(df) {
  result_df = data.frame()
  for (group in groups) {
    model = glm(expiremarker ~ age_40.49 + age_50.59 + age_60.69 
                             + age_70.79 + age_80. + gender + hgbmin_mortality + septicflag 
                             + ventmarker + vasopressor + surgeryflag 
                             + ihdflag + pvdflag + chfflag + esrfflag +
                             + sofatotal_dayLowestHmg + transfusedmarker,
              data = df[df$hb_group_mortality==group,],binomial(link = 'logit'))
    OR = exp(summary(model)$coefficients[,1])
    ci = exp(confint(model))
    p = summary(model)$coefficients[,4]
    results = cbind(OR, ci, p)
    print(group)
    print(results['transfusedmarker',])
    result_df = rbind(result_df,results['transfusedmarker',])
  }
  names(result_df) = c('OR','lower','upper','p-value')
  return(result_df)
}

print('Combined')
combined_lr = fit_glm(combined.data)
```

```{r propensity_estimation, eval = FALSE, include=FALSE, message=FALSE, warning=FALSE, results='hide'}
psm = function(df) {
  df$ps = 0
  for (group in groups) {
    df[df$hb_group_mortality==group,]$ps = ps(transfusedmarker ~ age_40.49 + age_50.59 + age_60.69 
                                           + age_70.79 + age_80. + gender + hgbmin_mortality + septicflag 
                                           + ventmarker + vasopressor + surgeryflag 
                                           + ihdflag + pvdflag + chfflag + esrfflag +
                                           + sofatotal_dayLowestHmg,
                                           data = df[df$hb_group_mortality==group,],
                                           n.trees=20000, interaction.depth=2, shrinkage=0.01,
                                           perm.test.iters=0,estimand = "ATT")$ps[,1]
  }
  return(df)
}

combined.data = psm(combined.data)
write.csv(combined.data,'data/combined_ps_mortality.csv')
```

```{r propesity_score_matching_load_data, echo=FALSE, message=FALSE, warning=FALSE, results='hide'}
combined.data = read.csv('data/combined_ps_mortality.csv')
```

```{r propensity_score_matching, eval=FALSE, echo=FALSE, message=FALSE, warning=FALSE, results='hide'}
match = function(df) {
  match_list = list()
  for (group in groups) {
      matched = Match(Tr = df$transfusedmarker,
                      X = df$ps, M = 1, estimand = "ATT", caliper = 0.01,
                      exact = FALSE, replace = FALSE, ties = FALSE)
      index.treated = matched$index.treated
      index.control = matched$index.control
      match_list[[group]] = rbind(df[index.treated,],df[index.control,])
  }
  matched_df = do.call(rbind, match_list)
  return(matched_df)
}

combined_matched = match(combined.data)
write.csv(combined_matched,'data/combined_matched_mortality.csv')
```

```{r propensity_score_matching_inference, echo=FALSE, message=FALSE, warning=FALSE, results='hide'}
combined_matched = read.csv('data/combined_matched_mortality.csv')

fit_glm = function(df) {
  result_df = data.frame()
  for (group in groups) {
    model = glm(expiremarker ~ transfusedmarker,
              data = df[df$hb_group_mortality==group,],binomial(link = 'logit'))
    OR = exp(summary(model)$coefficients[,1])
    ci = exp(confint(model))
    p = summary(model)$coefficients[,4]
    results = cbind(OR, ci, p)
    print(group)
    print(results)
    result_df = rbind(result_df,results['transfusedmarker',])
  }
  names(result_df) = c('OR','lower','upper','p-value')
  return(result_df)
}

print('Combined')
combined_psm = fit_glm(combined_matched)
```

```{r inverse_probability_treatment_weighting, echo=FALSE, message=FALSE, warning=FALSE, results='hide'}
iptw_glm = function(df) {
  result_df = data.frame()
  for (group in groups) {
    model = glm(expiremarker ~ transfusedmarker,
                data = df[df$hb_group_mortality==group,],
                family = binomial(link='logit'),
                weight = ps_weight)
    OR = exp(summary(model)$coefficients[,1])
    ci = exp(confint(model))
    p = summary(model)$coefficients[,4]
    results = cbind(OR, ci, p)
    print(group)
    print(results['transfusedmarker',])
    result_df = rbind(result_df,results['transfusedmarker',])
  }
  names(result_df) = c('OR','lower','upper','p-value')
  return(result_df)
}

combined.data$ID = seq.int(nrow(combined.data))

iptw = function(ps,t) {
  weight = t + ((1-t)*ps)/(1-ps)
  return(weight)
}

combined.data$ps_weight = mapply(iptw, combined.data$ps, combined.data$transfusedmarker)

print('Combined')
combined_iptw = iptw_glm(combined.data)
```

```{r doubly_robust_estimation, echo=FALSE, message=FALSE, warning=FALSE,results='hide'}
doubly_robust = function(df) {
  result_df = data.frame()
  for (group in groups) {
    model = glm(expiremarker ~ age_40.49 + age_50.59 + age_60.69 
                            + age_70.79 + age_80. + gender + hgbmin_mortality + septicflag 
                            + ventmarker + vasopressor + surgeryflag 
                            + ihdflag + pvdflag + chfflag + esrfflag +
                            + sofatotal_dayLowestHmg_quantile + transfusedmarker,
                data = df[df$hb_group_mortality==group,],
                family = binomial(link='logit'),
                weights = ps_weight)
    OR = exp(summary(model)$coefficients[,1])
    ci = exp(confint(model))
    p = summary(model)$coefficients[,4]
    results = cbind(OR, ci, p)
    print(group)
    print(results['transfusedmarker',])
    result_df = rbind(result_df,results['transfusedmarker',])
  }
  names(result_df) = c('OR','lower','upper','p-value')
  return(result_df)
}

print('Combined')
combined_dr = doubly_robust(combined.data)
```

```{r plotting_functions, eval=FALSE, echo=FALSE, message=FALSE, warning=FALSE,results='hide'}
make_plots = function(df_list) {
  par(mfrow=c(1,4))
  method_list = list('Multivariate Logistic Regression','Propensity Score Matching','IPTW','Doubly Robust Estimation')
  i = 1
  for (df in df_list) {
    plot(seq.int(length(groups)), df$OR, ylim = c(0,max(df$upper)+0.5), xaxt = "n", xlab ='Hb group', ylab='Odds Ratio',type = "l", main=method_list[[i]])
    axis(1, at=seq.int(length(groups)), labels=groups)
    #make polygon where coordinates start with lower limit and 
    # then upper limit in reverse order
    polygon(c(seq.int(length(groups)),rev(seq.int(length(groups)))),
            c(df$lower,rev(df$upper)),col = "grey75", border = FALSE)
    lines(seq.int(length(groups)), df$OR, lwd = 2)
    #add red lines on borders of polygon
    lines(seq.int(length(groups)), df$upper, col="red",lty=2)
    lines(seq.int(length(groups)), df$lower, col="red",lty=2)
    abline(h=1)
    i = i + 1
  }
}

```

```{r plotting_functions_2, echo=FALSE, message=FALSE, warning=FALSE,results='hide'}
make_plots = function(df_list) {
  par(mfrow=c(1,4))
  groups = c('7 to 7.99','8 to 8.99','9 to 9.99','10 to 11.99')
  method_list = list('Multivariate Logistic Regression','Propensity Score Matching','Inverse Probability of Treatment Weighting','Doubly Robust Estimation')
  color_list = list('#511845','#900C3F','#C70039','#F93800')
  i = 1
  for (df in df_list) {
    col = color_list[[i]]
    plot(seq.int(length(groups)), df$OR, ylim= c(0,2), pch=19, col=col,
         xlab="Transfusion Threshold (g/dL)", ylab="Odds Ratio", xaxt = "n", main=method_list[[i]],
         cex.lab=1.3, cex.axis=1.3, cex.main=2, cex.sub=1.3)
    axis(1, at=seq.int(length(groups)), labels=groups, cex.axis=1.3)
    # hack: we draw arrows but with very special "arrowheads"
    arrows(seq.int(length(groups)), df$upper, seq.int(length(groups)), df$lower,
           col=col,length=0.05, angle=90, code=3)
    abline(h=1)
    i = i + 1
  }
}
```

## Effect Of Blood Transfusion On Mortality

```{r, echo=FALSE,fig.height=5,fig.width=5,dpi=300}
df = combined_dr
col = '#283350'
groups = c('7.0 to 7.9','8.0 to 8.9','9.0 to 9.9','10.0 to 11.9')
plot(seq.int(length(groups)), df$OR, ylim= c(0,2), pch=19, col=col,
         xlab="Transfusion Threshold (g/dL)", ylab="Odds Ratio", xaxt = "n", main="A. Mortality",
         cex.lab=1, cex.axis=1, cex.main=1, cex.sub=1)
axis(1, at=seq.int(length(groups)), labels=groups, cex.axis=0.8)
arrows(seq.int(length(groups)), df$upper, seq.int(length(groups)), df$lower,
       col=col,length=0.05, angle=90, code=3)
abline(h=1,lty = 2)
dev.copy(png,width=5,height=5,units="in",res=300,'plots/mortality.png')
```

```{r, echo=FALSE, fig.height = 5, fig.width = 20, dpi=300}
df_list = list(combined_lr,combined_psm,combined_iptw,combined_dr)
make_plots(df_list)
dev.copy(png,width=20,height=5,units="in",res=300,'plots/mortality_supplement.png')
```

## Tabulation

```{r, echo=FALSE}
print(df_list)
```

```{r}
write.csv(combined_dr,'data/mortality_plot.csv')
```
